---
title: "Developing Data Products - Week 4"
author: "Koen Vermeulen"
date: "13-7-2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE)
setwd("~/Downloads/Data_Science_Specialization/Tests/Tests_R/DDP-Week3")
library(plotly)
library(tidyr)
```

## Reading & preparing data

```{r data, include=TRUE}
covid <- read.csv("~/Downloads/csv.csv")
covid_NL <- covid %>%
        mutate(dateRep = as.Date(dateRep, format = "%d/%m/%Y")) %>%
        filter(countriesAndTerritories == "Netherlands") %>%
        group_by(dateRep) %>%
                summarise(countriesAndTerritories = last(countriesAndTerritories),
                          cases = sum(cases),
                          deaths = sum(deaths)) %>%
        filter(cases != 0)
```

## Confirmed COVID-19 cases and deaths in the Netherlands

```{r confirmed over time, echo=FALSE}
plot <- plot_ly(data = covid_NL, 
                x = covid_NL$dateRep, 
                y = covid_NL$cases, 
                name = "Cases", 
                type = "scatter", 
                mode = "lines")
plot <- plot %>% add_trace(y = covid_NL$deaths,
                           name = "Deaths",
                           mode = "lines",
                           line = list(color = "rgb(200,0,0)"))
plot <- plot %>% layout(title = "Confirmed COVID-19 cases and deaths in the Netherlands over time",
         xaxis = list(title = "Date"),
         yaxis = list (title = "Cases and deaths"))
plot 
```

